/**
 * Demo Mock Data for Broadcast Campaigns
 * Extensive realistic broadcast campaigns for demonstration
 */

export const DEMO_BROADCASTS = [
  {
    id: 'broadcast-001',
    name: 'Voorjaars Promotie 2025',
    description: 'Lancering nieuwe collectie met exclusieve kortingscode',
    status: 'completed',
    template_id: 'promo_spring_2025',
    segment: { tags: ['customer', 'active'], created_after: '2024-01-01' },
    message_content: '🌸 Voorjaar is hier! Ontdek onze nieuwe collectie met 20% korting. Code: LENTE2025. Geldig tot 31 maart.',
    scheduled_at: '2025-03-01T09:00:00Z',
    sent_at: '2025-03-01T09:00:12Z',
    completed_at: '2025-03-01T09:47:33Z',
    statistics: {
      total_recipients: 2847,
      sent: 2847,
      delivered: 2801,
      failed: 46,
      opened: 2156,
      clicked: 847,
      replied: 234,
      conversion_rate: 29.7,
      revenue_generated: 47890.50,
    },
    created_at: '2025-02-28T14:22:00Z',
  },
  {
    id: 'broadcast-002',
    name: 'Appointment Reminder - Week 11',
    description: 'Automatische afspraak herinneringen voor geplande sessies',
    status: 'completed',
    template_id: 'appointment_reminder',
    segment: { tags: ['scheduled-appointment'], scheduled_date: '2025-03-10' },
    message_content: '📅 Herinnering: Je afspraak staat gepland op {{appointment_date}} om {{appointment_time}}. Bevestig met JA of wijzig met WIJZIG.',
    scheduled_at: '2025-03-08T08:00:00Z',
    sent_at: '2025-03-08T08:00:05Z',
    completed_at: '2025-03-08T08:12:18Z',
    statistics: {
      total_recipients: 423,
      sent: 423,
      delivered: 421,
      failed: 2,
      opened: 412,
      clicked: 89,
      replied: 387,
      conversion_rate: 91.5,
      revenue_generated: 0,
    },
    created_at: '2025-03-07T16:30:00Z',
  },
  {
    id: 'broadcast-003',
    name: 'Klant Tevredenheidsonderzoek Q1',
    description: 'Kwartaal feedback verzameling van actieve klanten',
    status: 'completed',
    template_id: 'survey_q1_2025',
    segment: { tags: ['customer'], last_purchase_within: 90 },
    message_content: '🎯 Help ons beter te worden! Vul onze 2-minuten enquête in en maak kans op €50 cadeaubon. Link: {{survey_link}}',
    scheduled_at: '2025-03-15T10:00:00Z',
    sent_at: '2025-03-15T10:00:08Z',
    completed_at: '2025-03-15T11:23:45Z',
    statistics: {
      total_recipients: 1634,
      sent: 1634,
      delivered: 1611,
      failed: 23,
      opened: 1287,
      clicked: 543,
      replied: 187,
      conversion_rate: 33.7,
      revenue_generated: 0,
    },
    created_at: '2025-03-14T11:45:00Z',
  },
  {
    id: 'broadcast-004',
    name: 'Flash Sale - 4 Uur Actie',
    description: 'Beperkte tijd aanbod voor top producten',
    status: 'sending',
    template_id: 'flash_sale',
    segment: { tags: ['vip', 'high-value'], total_spent_over: 500 },
    message_content: '⚡ FLASH SALE! 4 uur lang 40% korting op geselecteerde items. VIP early access. Shop nu: {{shop_link}}',
    scheduled_at: '2025-03-20T14:00:00Z',
    sent_at: '2025-03-20T14:00:03Z',
    completed_at: null,
    statistics: {
      total_recipients: 892,
      sent: 654,
      delivered: 641,
      failed: 13,
      opened: 487,
      clicked: 213,
      replied: 67,
      conversion_rate: 32.5,
      revenue_generated: 18450.75,
    },
    created_at: '2025-03-20T13:15:00Z',
  },
  {
    id: 'broadcast-005',
    name: 'Nieuwsbrief Maart - Productlancering',
    description: 'Maandelijkse nieuwsbrief met nieuwe feature aankondiging',
    status: 'scheduled',
    template_id: 'newsletter_monthly',
    segment: { tags: ['subscriber'], opt_in: true },
    message_content: '📰 Maart Update: Nieuwe AI-gestuurde aanbevelingen, klantcase studies, en exclusieve tips. Lees meer: {{newsletter_link}}',
    scheduled_at: '2025-03-25T09:00:00Z',
    sent_at: null,
    completed_at: null,
    statistics: {
      total_recipients: 3421,
      sent: 0,
      delivered: 0,
      failed: 0,
      opened: 0,
      clicked: 0,
      replied: 0,
      conversion_rate: 0,
      revenue_generated: 0,
    },
    created_at: '2025-03-18T10:30:00Z',
  },
  {
    id: 'broadcast-006',
    name: 'Winback Campagne - Inactieve Klanten',
    description: 'Heractivatie aanbod voor klanten 6+ maanden inactief',
    status: 'completed',
    template_id: 'winback_offer',
    segment: { tags: ['inactive'], last_activity_before: '2024-09-01' },
    message_content: '💔 We missen je! Kom terug met 30% welkomstkorting. Jouw favorieten wachten op je. Code: WELKOMTERUG',
    scheduled_at: '2025-03-05T11:00:00Z',
    sent_at: '2025-03-05T11:00:15Z',
    completed_at: '2025-03-05T12:45:22Z',
    statistics: {
      total_recipients: 1876,
      sent: 1876,
      delivered: 1823,
      failed: 53,
      opened: 923,
      clicked: 234,
      replied: 89,
      conversion_rate: 12.8,
      revenue_generated: 8930.25,
    },
    created_at: '2025-03-04T15:00:00Z',
  },
  {
    id: 'broadcast-007',
    name: 'Black Friday Preview - VIP Access',
    description: 'Vroege toegang voor loyale klanten tot Black Friday deals',
    status: 'draft',
    template_id: 'blackfriday_preview',
    segment: { tags: ['vip', 'loyalty-tier-gold'], total_orders_over: 10 },
    message_content: '🎁 VIP Early Access! Black Friday deals nu al beschikbaar. 50% korting + gratis verzending. Shop: {{bf_link}}',
    scheduled_at: '2025-11-22T06:00:00Z',
    sent_at: null,
    completed_at: null,
    statistics: {
      total_recipients: 567,
      sent: 0,
      delivered: 0,
      failed: 0,
      opened: 0,
      clicked: 0,
      replied: 0,
      conversion_rate: 0,
      revenue_generated: 0,
    },
    created_at: '2025-03-19T09:00:00Z',
  },
  {
    id: 'broadcast-008',
    name: 'Webinar Uitnodiging - Marketing Automation',
    description: 'Gratis webinar voor prospects en klanten',
    status: 'completed',
    template_id: 'webinar_invite',
    segment: { tags: ['lead', 'prospect', 'customer'], interested_in: 'automation' },
    message_content: '🎓 Gratis Webinar: "WhatsApp Marketing Automation Masterclass" - 28 maart, 14:00. Registreer: {{webinar_link}}',
    scheduled_at: '2025-03-18T10:00:00Z',
    sent_at: '2025-03-18T10:00:07Z',
    completed_at: '2025-03-18T11:34:52Z',
    statistics: {
      total_recipients: 2134,
      sent: 2134,
      delivered: 2098,
      failed: 36,
      opened: 1645,
      clicked: 892,
      replied: 312,
      conversion_rate: 42.5,
      revenue_generated: 0,
    },
    created_at: '2025-03-15T13:20:00Z',
  },
  {
    id: 'broadcast-009',
    name: 'Order Verzendbevestiging Batch',
    description: 'Bulk verzendbevestigingen voor dagelijkse orders',
    status: 'completed',
    template_id: 'shipping_confirmation',
    segment: { tags: ['order-shipped'], shipped_date: '2025-03-19' },
    message_content: '📦 Je bestelling is verzonden! Track & Trace: {{tracking_code}}. Verwachte levering: {{delivery_date}}.',
    scheduled_at: '2025-03-19T18:00:00Z',
    sent_at: '2025-03-19T18:00:02Z',
    completed_at: '2025-03-19T18:23:11Z',
    statistics: {
      total_recipients: 734,
      sent: 734,
      delivered: 729,
      failed: 5,
      opened: 678,
      clicked: 512,
      replied: 43,
      conversion_rate: 92.4,
      revenue_generated: 0,
    },
    created_at: '2025-03-19T17:30:00Z',
  },
  {
    id: 'broadcast-010',
    name: 'Birthday Campaign - Maart Celebraties',
    description: 'Automatische verjaardagswensen met exclusieve korting',
    status: 'completed',
    template_id: 'birthday_wishes',
    segment: { tags: ['customer'], birthday_month: 3 },
    message_content: '🎂 Gefeliciteerd met je verjaardag! Geniet van 25% korting als cadeau van ons. Code: VERJAARDAG{{year}}',
    scheduled_at: '2025-03-01T08:00:00Z',
    sent_at: '2025-03-01T08:00:09Z',
    completed_at: '2025-03-01T08:45:33Z',
    statistics: {
      total_recipients: 412,
      sent: 412,
      delivered: 408,
      failed: 4,
      opened: 389,
      clicked: 276,
      replied: 198,
      conversion_rate: 67.6,
      revenue_generated: 12340.80,
    },
    created_at: '2025-02-28T16:00:00Z',
  },
  {
    id: 'broadcast-011',
    name: 'Product Terugkoppeling na Aankoop',
    description: 'Follow-up vragen na productlevering voor feedback',
    status: 'completed',
    template_id: 'post_purchase_feedback',
    segment: { tags: ['delivered'], delivery_date_days_ago: 7 },
    message_content: '⭐ Hoe bevalt je aankoop? Deel je ervaring en ontvang 10% korting op je volgende order. Review: {{review_link}}',
    scheduled_at: '2025-03-12T10:00:00Z',
    sent_at: '2025-03-12T10:00:11Z',
    completed_at: '2025-03-12T11:12:47Z',
    statistics: {
      total_recipients: 623,
      sent: 623,
      delivered: 618,
      failed: 5,
      opened: 534,
      clicked: 287,
      replied: 156,
      conversion_rate: 46.4,
      revenue_generated: 3450.60,
    },
    created_at: '2025-03-11T14:15:00Z',
  },
  {
    id: 'broadcast-012',
    name: 'Abandoned Cart Serie - Dag 1',
    description: 'Eerste herinnering voor verlaten winkelwagens',
    status: 'sending',
    template_id: 'cart_reminder_day1',
    segment: { tags: ['cart-abandoned'], abandoned_hours_ago: 24 },
    message_content: '🛒 Je hebt items in je winkelwagen laten staan. Nog vragen? We helpen graag! Bekijk winkelwagen: {{cart_link}}',
    scheduled_at: '2025-03-20T12:00:00Z',
    sent_at: '2025-03-20T12:00:06Z',
    completed_at: null,
    statistics: {
      total_recipients: 328,
      sent: 243,
      delivered: 238,
      failed: 5,
      opened: 187,
      clicked: 94,
      replied: 31,
      conversion_rate: 38.6,
      revenue_generated: 4230.90,
    },
    created_at: '2025-03-20T11:30:00Z',
  },
  {
    id: 'broadcast-013',
    name: 'Seizoensoverzicht - Winter 2024/2025',
    description: 'Terugblik op afgelopen seizoen met highlights',
    status: 'completed',
    template_id: 'season_recap',
    segment: { tags: ['customer', 'subscriber'], active_in_period: 'winter-2024' },
    message_content: '❄️ Winter Recap: Jouw favoriete producten, onze bestsellers, en wat er komt in het voorjaar. Lees meer: {{recap_link}}',
    scheduled_at: '2025-02-28T15:00:00Z',
    sent_at: '2025-02-28T15:00:14Z',
    completed_at: '2025-02-28T16:23:09Z',
    statistics: {
      total_recipients: 1923,
      sent: 1923,
      delivered: 1889,
      failed: 34,
      opened: 1456,
      clicked: 623,
      replied: 189,
      conversion_rate: 33.0,
      revenue_generated: 8760.40,
    },
    created_at: '2025-02-27T10:00:00Z',
  },
  {
    id: 'broadcast-014',
    name: 'Restock Alert - Populaire Items',
    description: 'Notificatie voor klanten die interesse toonden in uitverkochte items',
    status: 'scheduled',
    template_id: 'restock_notification',
    segment: { tags: ['waitlist'], product_ids: ['prod-123', 'prod-456', 'prod-789'] },
    message_content: '🔔 RESTOCK ALERT! De items op je verlanglijst zijn weer beschikbaar. Snel zijn want beperkte voorraad! Shop: {{product_link}}',
    scheduled_at: '2025-03-22T09:00:00Z',
    sent_at: null,
    completed_at: null,
    statistics: {
      total_recipients: 567,
      sent: 0,
      delivered: 0,
      failed: 0,
      opened: 0,
      clicked: 0,
      replied: 0,
      conversion_rate: 0,
      revenue_generated: 0,
    },
    created_at: '2025-03-21T16:45:00Z',
  },
  {
    id: 'broadcast-015',
    name: 'Referral Program Launch',
    description: 'Introductie nieuw doorverwijsprogramma met incentives',
    status: 'completed',
    template_id: 'referral_launch',
    segment: { tags: ['customer', 'satisfied'], nps_score_over: 8 },
    message_content: '🎁 Nieuw! Deel ADSapp met vrienden en verdien beiden €50 credit. Jouw unieke link: {{referral_link}}',
    scheduled_at: '2025-03-10T11:00:00Z',
    sent_at: '2025-03-10T11:00:08Z',
    completed_at: '2025-03-10T12:34:27Z',
    statistics: {
      total_recipients: 1456,
      sent: 1456,
      delivered: 1432,
      failed: 24,
      opened: 1145,
      clicked: 534,
      replied: 267,
      conversion_rate: 37.3,
      revenue_generated: 15670.00,
    },
    created_at: '2025-03-09T14:30:00Z',
  },
]

export const DEMO_BROADCAST_STATS = {
  total_campaigns: DEMO_BROADCASTS.length,
  completed_campaigns: DEMO_BROADCASTS.filter(b => b.status === 'completed').length,
  total_messages_sent: DEMO_BROADCASTS.reduce((sum, b) => sum + b.statistics.sent, 0),
  total_delivered: DEMO_BROADCASTS.reduce((sum, b) => sum + b.statistics.delivered, 0),
  total_revenue: DEMO_BROADCASTS.reduce((sum, b) => sum + b.statistics.revenue_generated, 0),
  avg_open_rate: (
    DEMO_BROADCASTS.filter(b => b.statistics.sent > 0).reduce(
      (sum, b) => sum + (b.statistics.opened / b.statistics.sent) * 100,
      0
    ) / DEMO_BROADCASTS.filter(b => b.statistics.sent > 0).length
  ).toFixed(1),
  avg_click_rate: (
    DEMO_BROADCASTS.filter(b => b.statistics.sent > 0).reduce(
      (sum, b) => sum + (b.statistics.clicked / b.statistics.sent) * 100,
      0
    ) / DEMO_BROADCASTS.filter(b => b.statistics.sent > 0).length
  ).toFixed(1),
  avg_conversion_rate: (
    DEMO_BROADCASTS.filter(b => b.statistics.sent > 0).reduce(
      (sum, b) => sum + b.statistics.conversion_rate,
      0
    ) / DEMO_BROADCASTS.filter(b => b.statistics.sent > 0).length
  ).toFixed(1),
}
