/**
 * Demo Mock Data for Drip Campaigns
 * Extensive realistic drip campaign sequences for demonstration
 */

export const DEMO_DRIP_CAMPAIGNS = [
  {
    id: 'drip-001',
    name: 'Onboarding Series - Nieuwe Klanten',
    description: '7-daagse welkomstreeks met productintroductie en tips',
    status: 'active',
    trigger_type: 'tag_added',
    trigger_config: { tag: 'new-customer' },
    subscribers: {
      total: 3421,
      active: 2847,
      paused: 134,
      completed: 412,
      stopped: 28,
    },
    performance: {
      completion_rate: 83.2,
      avg_engagement_rate: 68.5,
      conversion_rate: 34.7,
      revenue_per_subscriber: 47.80,
    },
    steps: [
      {
        step_number: 1,
        delay: { value: 0, unit: 'minutes' },
        message_template: 'onboarding_welcome',
        message_content: '👋 Welkom bij ADSapp! We zijn blij je te zien. Hier is wat je moet weten om te beginnen...',
        sent: 3421,
        opened: 3198,
        clicked: 2456,
        replied: 892,
      },
      {
        step_number: 2,
        delay: { value: 1, unit: 'days' },
        message_template: 'onboarding_features',
        message_content: '🚀 Dag 2: Ontdek onze krachtigste features. Hier zijn 3 dingen die je vandaag kunt proberen...',
        sent: 3287,
        opened: 2934,
        clicked: 2123,
        replied: 634,
      },
      {
        step_number: 3,
        delay: { value: 3, unit: 'days' },
        message_template: 'onboarding_tips',
        message_content: '💡 Pro Tips: Haal het maximale uit ADSapp met deze 5 insider tips van ervaren gebruikers...',
        sent: 3156,
        opened: 2789,
        clicked: 1876,
        replied: 456,
      },
      {
        step_number: 4,
        delay: { value: 5, unit: 'days' },
        message_template: 'onboarding_case_study',
        message_content: '📊 Success Story: Ontdek hoe Bedrijf X hun conversie met 300% verhoogde met ADSapp...',
        sent: 3023,
        opened: 2567,
        clicked: 1634,
        replied: 312,
      },
      {
        step_number: 5,
        delay: { value: 7, unit: 'days' },
        message_template: 'onboarding_upgrade',
        message_content: '⭐ Ready to level up? Upgrade naar Pro en ontvang 20% korting deze maand. Code: NEWPRO20',
        sent: 2912,
        opened: 2345,
        clicked: 1423,
        replied: 267,
      },
    ],
    created_at: '2025-01-15T10:00:00Z',
    last_modified: '2025-03-10T14:23:00Z',
  },
  {
    id: 'drip-002',
    name: 'Lead Nurture - Prospects naar Klanten',
    description: '14-daagse educatieve serie voor koude leads',
    status: 'active',
    trigger_type: 'tag_added',
    trigger_config: { tag: 'cold-lead' },
    subscribers: {
      total: 1876,
      active: 1423,
      paused: 89,
      completed: 334,
      stopped: 30,
    },
    performance: {
      completion_rate: 75.8,
      avg_engagement_rate: 54.2,
      conversion_rate: 18.9,
      revenue_per_subscriber: 89.40,
    },
    steps: [
      {
        step_number: 1,
        delay: { value: 0, unit: 'hours' },
        message_template: 'lead_intro',
        message_content: '🤝 Bedankt voor je interesse! Laat me je laten zien waarom 10.000+ bedrijven voor ons kiezen...',
        sent: 1876,
        opened: 1623,
        clicked: 1089,
        replied: 412,
      },
      {
        step_number: 2,
        delay: { value: 2, unit: 'days' },
        message_template: 'lead_problem',
        message_content: '🎯 Herken je dit? 73% van bedrijven worstelt met WhatsApp beheer. Hier is hoe wij dat oplossen...',
        sent: 1789,
        opened: 1534,
        clicked: 967,
        replied: 289,
      },
      {
        step_number: 3,
        delay: { value: 5, unit: 'days' },
        message_template: 'lead_solution',
        message_content: '💼 Case Study: Hoe Bedrijf Y 50% tijd bespaarde en 200% meer conversie behaalde...',
        sent: 1712,
        opened: 1423,
        clicked: 845,
        replied: 198,
      },
      {
        step_number: 4,
        delay: { value: 7, unit: 'days' },
        message_template: 'lead_demo',
        message_content: '🎥 Zie het in actie! Boek een persoonlijke 15-min demo en ontvang gratis setup hulp...',
        sent: 1645,
        opened: 1334,
        clicked: 789,
        replied: 267,
      },
      {
        step_number: 5,
        delay: { value: 10, unit: 'days' },
        message_template: 'lead_testimonials',
        message_content: '⭐ "Beste investering dit jaar!" - lees waarom klanten gemiddeld 4.8/5 sterren geven...',
        sent: 1567,
        opened: 1245,
        clicked: 678,
        replied: 156,
      },
      {
        step_number: 6,
        delay: { value: 14, unit: 'days' },
        message_template: 'lead_offer',
        message_content: '🎁 Laatste kans: Start vandaag met 30% korting + 1 maand gratis. Claim aanbieding: {{offer_link}}',
        sent: 1489,
        opened: 1178,
        clicked: 623,
        replied: 189,
      },
    ],
    created_at: '2025-01-20T09:00:00Z',
    last_modified: '2025-03-15T11:12:00Z',
  },
  {
    id: 'drip-003',
    name: 'Re-engagement - Inactieve Gebruikers',
    description: '21-daagse winback campagne voor dormant accounts',
    status: 'active',
    trigger_type: 'time_based',
    trigger_config: { inactive_days: 60 },
    subscribers: {
      total: 892,
      active: 634,
      paused: 45,
      completed: 198,
      stopped: 15,
    },
    performance: {
      completion_rate: 71.3,
      avg_engagement_rate: 42.7,
      conversion_rate: 22.1,
      revenue_per_subscriber: 112.60,
    },
    steps: [
      {
        step_number: 1,
        delay: { value: 0, unit: 'hours' },
        message_template: 'winback_miss_you',
        message_content: '💔 We missen je! Het is al een tijdje geleden. Hier is wat je gemist hebt...',
        sent: 892,
        opened: 712,
        clicked: 456,
        replied: 178,
      },
      {
        step_number: 2,
        delay: { value: 3, unit: 'days' },
        message_template: 'winback_updates',
        message_content: '🆕 Nieuwe features sinds je laatste bezoek: AI automation, analytics dashboard, en meer!',
        sent: 834,
        opened: 667,
        clicked: 389,
        replied: 123,
      },
      {
        step_number: 3,
        delay: { value: 7, unit: 'days' },
        message_template: 'winback_offer',
        message_content: '🎁 Speciaal voor jou: 40% comeback korting + gratis setup session. Code: WELKOMTERUG',
        sent: 789,
        opened: 623,
        clicked: 367,
        replied: 156,
      },
      {
        step_number: 4,
        delay: { value: 14, unit: 'days' },
        message_template: 'winback_final',
        message_content: '⏰ Laatste reminder: Je comeback aanbieding verloopt over 7 dagen. Claim nu: {{offer_link}}',
        sent: 723,
        opened: 567,
        clicked: 312,
        replied: 98,
      },
    ],
    created_at: '2025-02-01T10:00:00Z',
    last_modified: '2025-03-12T16:45:00Z',
  },
  {
    id: 'drip-004',
    name: 'Product Education - Advanced Features',
    description: '10-daagse deep-dive in advanced functionaliteit',
    status: 'active',
    trigger_type: 'tag_added',
    trigger_config: { tag: 'power-user-candidate' },
    subscribers: {
      total: 567,
      active: 456,
      paused: 23,
      completed: 78,
      stopped: 10,
    },
    performance: {
      completion_rate: 82.5,
      avg_engagement_rate: 76.3,
      conversion_rate: 45.2,
      revenue_per_subscriber: 234.70,
    },
    steps: [
      {
        step_number: 1,
        delay: { value: 0, unit: 'hours' },
        message_template: 'advanced_intro',
        message_content: '🚀 Ready voor advanced features? Laat me je laten zien hoe pro\'s ADSapp gebruiken...',
        sent: 567,
        opened: 534,
        clicked: 478,
        replied: 234,
      },
      {
        step_number: 2,
        delay: { value: 2, unit: 'days' },
        message_template: 'advanced_automation',
        message_content: '🤖 Automation Masterclass: Bouw complexe workflows met branching logic en AI decisions...',
        sent: 556,
        opened: 523,
        clicked: 456,
        replied: 198,
      },
      {
        step_number: 3,
        delay: { value: 5, unit: 'days' },
        message_template: 'advanced_analytics',
        message_content: '📊 Analytics Deep Dive: Track ROI, customer journey, en predictive insights...',
        sent: 545,
        opened: 512,
        clicked: 423,
        replied: 167,
      },
      {
        step_number: 4,
        delay: { value: 8, unit: 'days' },
        message_template: 'advanced_integrations',
        message_content: '🔗 CRM Integration: Sync met Salesforce, HubSpot, Pipedrive voor unified data...',
        sent: 534,
        opened: 498,
        clicked: 389,
        replied: 145,
      },
      {
        step_number: 5,
        delay: { value: 10, unit: 'days' },
        message_template: 'advanced_certification',
        message_content: '🎓 Claim je Power User certificaat! Complete de challenge en ontvang exclusieve badge...',
        sent: 523,
        opened: 487,
        clicked: 356,
        replied: 189,
      },
    ],
    created_at: '2025-02-10T11:00:00Z',
    last_modified: '2025-03-18T09:30:00Z',
  },
  {
    id: 'drip-005',
    name: 'Customer Success - Post-Purchase',
    description: '30-daagse support en upsell journey na aankoop',
    status: 'active',
    trigger_type: 'tag_added',
    trigger_config: { tag: 'purchase-completed' },
    subscribers: {
      total: 2134,
      active: 1876,
      paused: 67,
      completed: 178,
      stopped: 13,
    },
    performance: {
      completion_rate: 88.6,
      avg_engagement_rate: 72.8,
      conversion_rate: 28.4,
      revenue_per_subscriber: 156.90,
    },
    steps: [
      {
        step_number: 1,
        delay: { value: 0, unit: 'hours' },
        message_template: 'purchase_thank_you',
        message_content: '🎉 Bedankt voor je aankoop! Hier is je order bevestiging en setup guide...',
        sent: 2134,
        opened: 2089,
        clicked: 1876,
        replied: 634,
      },
      {
        step_number: 2,
        delay: { value: 3, unit: 'days' },
        message_template: 'purchase_check_in',
        message_content: '👋 Hoe gaat het? Heb je hulp nodig bij de setup? Ons support team staat klaar...',
        sent: 2098,
        opened: 1923,
        clicked: 1567,
        replied: 489,
      },
      {
        step_number: 3,
        delay: { value: 7, unit: 'days' },
        message_template: 'purchase_tips',
        message_content: '💡 Week 1 tips: Maximaliseer je ROI met deze 5 best practices van top performers...',
        sent: 2067,
        opened: 1834,
        clicked: 1423,
        replied: 356,
      },
      {
        step_number: 4,
        delay: { value: 14, unit: 'days' },
        message_template: 'purchase_advanced',
        message_content: '🚀 Ready voor meer? Ontdek advanced features die je conversie kunnen verdubbelen...',
        sent: 2023,
        opened: 1767,
        clicked: 1289,
        replied: 289,
      },
      {
        step_number: 5,
        delay: { value: 21, unit: 'days' },
        message_template: 'purchase_upsell',
        message_content: '⭐ Upgrade naar Enterprise en ontvang: AI-powered insights, dedicated support, +50% capacity...',
        sent: 1989,
        opened: 1698,
        clicked: 1123,
        replied: 267,
      },
      {
        step_number: 6,
        delay: { value: 30, unit: 'days' },
        message_template: 'purchase_review',
        message_content: '📝 Een maand geleden! Hoe bevalt ADSapp? Deel je ervaring en help anderen kiezen...',
        sent: 1956,
        opened: 1634,
        clicked: 1045,
        replied: 456,
      },
    ],
    created_at: '2025-01-25T14:00:00Z',
    last_modified: '2025-03-19T10:15:00Z',
  },
  {
    id: 'drip-006',
    name: 'Seasonal Engagement - Holiday Series',
    description: 'Feestdagen themacampagne met speciale aanbiedingen',
    status: 'paused',
    trigger_type: 'date_based',
    trigger_config: { start_date: '2025-12-01', end_date: '2025-12-31' },
    subscribers: {
      total: 4567,
      active: 0,
      paused: 4567,
      completed: 0,
      stopped: 0,
    },
    performance: {
      completion_rate: 0,
      avg_engagement_rate: 0,
      conversion_rate: 0,
      revenue_per_subscriber: 0,
    },
    steps: [
      {
        step_number: 1,
        delay: { value: 0, unit: 'days' },
        message_template: 'holiday_early_bird',
        message_content: '🎄 Early Bird: Start je feestdagen campagnes nu en bespaar 30% op je setup...',
        sent: 0,
        opened: 0,
        clicked: 0,
        replied: 0,
      },
      {
        step_number: 2,
        delay: { value: 7, unit: 'days' },
        message_template: 'holiday_templates',
        message_content: '✨ Gratis feestdagen templates: 20 bewezen WhatsApp campaigns voor maximale verkoop...',
        sent: 0,
        opened: 0,
        clicked: 0,
        replied: 0,
      },
      {
        step_number: 3,
        delay: { value: 14, unit: 'days' },
        message_template: 'holiday_flash_sale',
        message_content: '⚡ Flash Sale: 48 uur lang 50% korting op alle plannen. Claim nu: {{sale_link}}',
        sent: 0,
        opened: 0,
        clicked: 0,
        replied: 0,
      },
      {
        step_number: 4,
        delay: { value: 21, unit: 'days' },
        message_template: 'holiday_year_end',
        message_content: '🎁 Year-End Special: Lock in 2025 pricing + bonus features. Laatste kans!',
        sent: 0,
        opened: 0,
        clicked: 0,
        replied: 0,
      },
    ],
    created_at: '2025-03-01T12:00:00Z',
    last_modified: '2025-03-01T12:00:00Z',
  },
  {
    id: 'drip-007',
    name: 'Trial Conversion - Free to Paid',
    description: '14-daagse trial maximalisatie en conversie strategie',
    status: 'active',
    trigger_type: 'tag_added',
    trigger_config: { tag: 'trial-started' },
    subscribers: {
      total: 3421,
      active: 2934,
      paused: 123,
      completed: 334,
      stopped: 30,
    },
    performance: {
      completion_rate: 78.9,
      avg_engagement_rate: 65.4,
      conversion_rate: 41.7,
      revenue_per_subscriber: 67.80,
    },
    steps: [
      {
        step_number: 1,
        delay: { value: 0, unit: 'hours' },
        message_template: 'trial_welcome',
        message_content: '🚀 Je trial is begonnen! Hier zijn 3 dingen om vandaag te doen voor maximaal resultaat...',
        sent: 3421,
        opened: 3234,
        clicked: 2876,
        replied: 1023,
      },
      {
        step_number: 2,
        delay: { value: 2, unit: 'days' },
        message_template: 'trial_milestone',
        message_content: '📈 Dag 2: Je eerste milestone! Bekijk je resultaten en volgende stappen...',
        sent: 3356,
        opened: 3087,
        clicked: 2634,
        replied: 789,
      },
      {
        step_number: 3,
        delay: { value: 5, unit: 'days' },
        message_template: 'trial_halfway',
        message_content: '⏱️ Halfway point! Review je progress en unlock advanced features voor de 2e helft...',
        sent: 3289,
        opened: 2956,
        clicked: 2423,
        replied: 634,
      },
      {
        step_number: 4,
        delay: { value: 10, unit: 'days' },
        message_template: 'trial_upgrade_offer',
        message_content: '⭐ Bijna klaar! Upgrade nu en ontvang 20% korting + gratis extra maand. Code: TRIAL20',
        sent: 3198,
        opened: 2845,
        clicked: 2234,
        replied: 567,
      },
      {
        step_number: 5,
        delay: { value: 13, unit: 'days' },
        message_template: 'trial_last_chance',
        message_content: '⏰ Laatste dag! Don\'t lose je data en progress. Upgrade nu en blijf groeien...',
        sent: 3134,
        opened: 2767,
        clicked: 2123,
        replied: 489,
      },
    ],
    created_at: '2025-02-05T09:00:00Z',
    last_modified: '2025-03-17T13:22:00Z',
  },
  {
    id: 'drip-008',
    name: 'Referral Incentive - Advocacy Program',
    description: '30-daagse referral promotion voor tevreden klanten',
    status: 'active',
    trigger_type: 'tag_added',
    trigger_config: { tag: 'high-satisfaction', nps_score: 9 },
    subscribers: {
      total: 1234,
      active: 1023,
      paused: 45,
      completed: 156,
      stopped: 10,
    },
    performance: {
      completion_rate: 85.7,
      avg_engagement_rate: 71.2,
      conversion_rate: 52.8,
      revenue_per_subscriber: 289.40,
    },
    steps: [
      {
        step_number: 1,
        delay: { value: 0, unit: 'hours' },
        message_template: 'referral_intro',
        message_content: '🌟 We zien dat je ADSapp geweldig vindt! Deel met vrienden en verdien €100 per referral...',
        sent: 1234,
        opened: 1178,
        clicked: 1023,
        replied: 567,
      },
      {
        step_number: 2,
        delay: { value: 7, unit: 'days' },
        message_template: 'referral_reminder',
        message_content: '💰 Reminder: Je unieke referral link. Deel op LinkedIn, email, of WhatsApp...',
        sent: 1198,
        opened: 1134,
        clicked: 945,
        replied: 423,
      },
      {
        step_number: 3,
        delay: { value: 14, unit: 'days' },
        message_template: 'referral_bonus',
        message_content: '🎁 Bonus actie: Verwijs 3+ vrienden deze maand en ontvang extra €150 + VIP status...',
        sent: 1167,
        opened: 1089,
        clicked: 878,
        replied: 356,
      },
      {
        step_number: 4,
        delay: { value: 21, unit: 'days' },
        message_template: 'referral_leaderboard',
        message_content: '🏆 Top Referrers deze maand: Sta jij in de top 10? Extra prizes voor #1, #2, #3...',
        sent: 1145,
        opened: 1056,
        clicked: 834,
        replied: 289,
      },
      {
        step_number: 5,
        delay: { value: 30, unit: 'days' },
        message_template: 'referral_thank_you',
        message_content: '🙏 Bedankt voor je referrals! Hier is je earnings summary en exclusive rewards...',
        sent: 1123,
        opened: 1034,
        clicked: 789,
        replied: 234,
      },
    ],
    created_at: '2025-02-15T10:30:00Z',
    last_modified: '2025-03-16T14:45:00Z',
  },
]

export const DEMO_DRIP_STATS = {
  total_campaigns: DEMO_DRIP_CAMPAIGNS.length,
  active_campaigns: DEMO_DRIP_CAMPAIGNS.filter(d => d.status === 'active').length,
  total_subscribers: DEMO_DRIP_CAMPAIGNS.reduce((sum, d) => sum + d.subscribers.total, 0),
  active_subscribers: DEMO_DRIP_CAMPAIGNS.reduce((sum, d) => sum + d.subscribers.active, 0),
  avg_completion_rate: (
    DEMO_DRIP_CAMPAIGNS.reduce((sum, d) => sum + d.performance.completion_rate, 0) /
    DEMO_DRIP_CAMPAIGNS.length
  ).toFixed(1),
  avg_conversion_rate: (
    DEMO_DRIP_CAMPAIGNS.reduce((sum, d) => sum + d.performance.conversion_rate, 0) /
    DEMO_DRIP_CAMPAIGNS.length
  ).toFixed(1),
  total_revenue: DEMO_DRIP_CAMPAIGNS.reduce(
    (sum, d) => sum + d.subscribers.total * d.performance.revenue_per_subscriber,
    0
  ).toFixed(2),
}
